// (c) Copyright 2015 Cloudera, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package com.cloudera.director.aws;

/**
 * Director tags for cloud resources and instances.
 */
public final class Tags {

  /**
   * Director tags for cloud resources.
   */
  public enum ResourceTags {
    /**
     * The name of the resource.
     */
    RESOURCE_NAME("Name"),

    /**
     * The virtual instance ID as generated by Cloudera Director.
     */
    CLOUDERA_DIRECTOR_ID("Cloudera-Director-Id"),

    /**
     * The virtual instance ID as generated by Cloudera Director.
     */
    CLOUDERA_DIRECTOR_TEMPLATE_NAME("Cloudera-Director-Template-Name");

    private final String tagName;

    ResourceTags(String tagName) {
      this.tagName = tagName;
    }

    /**
     * Gets the tag's key.
     * Note that you should always call this method to get the tag's key, and not the
     * {@link ResourceTags#valueOf(String)} method.
     * @return tag's key name
     */
    public String getTagKey() {
      return tagName;
    }
  }

  /**
   * Director tags specifically for cloud instances.
   */
  public enum InstanceTags {
    /**
     * The instance owner.
     */
    OWNER("owner");

    private final String tagName;

    InstanceTags(String tagName) {
      this.tagName = tagName;
    }

    /**
     * Gets the tag's key.
     * Note that you should always call this method to get the tag's key, and not the
     * {@link InstanceTags#valueOf(String)} method.
     * @return tag's key name
     */
    public String getTagKey() {
      return tagName;
    }
  }


  /**
   * Private constructor to prevent instantiation.
   */
  private Tags() {
  }
}
