// (c) Copyright 2015 Cloudera, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package com.cloudera.director.aws;

/**
 * Common tags for cloud resources.
 */
public final class Tags {

  /**
   * Private constructor to prevent instantiation.
   */
  private Tags() {
  }

  /**
   * The virtual instance ID as generated by Cloudera Director.
   */
  public static final String CLOUDERA_DIRECTOR_ID = "Cloudera-Director-Id";

  /**
   * The name of the instance template used as a specification.
   */
  public static final String CLOUDERA_DIRECTOR_TEMPLATE_NAME = "Cloudera-Director-Template-Name";
}
